runtime: plugin
action:
  title: Web UI
  description: >-
    Starts Web UI. Example: "web", "web --foreground", "web stop"
  alias:
    - ui
  arguments:
    - name: op
      title: Operation
      description: "Operates the web server. Optional. Allowed: [stop]"
      type: string
      enum: [start, stop]
      default: start
  options:
    - name: port
      shorthand: p
      title: Port
      description: Web server port
      type: integer
      default: 8080
    - name: foreground
      title: Foreground
      description: Run server in foreground. By default Web UI starts in background.
      type: boolean
      default: false
    - name: proxy-client
      title: Proxy client
      description: Proxies to client web server, useful in local development
      type: string
      default: ""
    - name: ui-assets
      title: Client Assets Directory
      description: >-
        Specifies a local directory path to override built-in client assets.
      type: string
      default: ""
    - name: swagger-ui
      title: Swagger UI Directory
      description: Serve swagger.json on /api/swagger.json and Swagger UI on /api/swagger-ui from specified directory.
      type: string
      default: ""
    - name: no-ui
      title: No UI
      description: run server without UI
      type: boolean
      default: false
    - name: auth_user
      title: HTTP Auth User
      default: ""
      process:
        - processor: keyring.GetKeyValue
          options:
            key: web_auth_user
    - name: auth_password
      title: HTTP Auth Password
      default: ""
      process:
        - processor: keyring.GetKeyValue
          options:
            key: web_auth_password