action:
  title: RJSF Example of Numbers
  description: RJSF Numbers arguments
  image: alpine:latest
  command: ["sh", "-c", "for i in $(seq 60); do echo $$i; sleep 1; done"]
  arguments:
    - name: float
      title: Float
    - name: integer
      title: Integer
      default: 5
      type: integer
    - name: numberConstrained
      title: Number with constraints
      type: integer
      minimum: 50
      maximum: 100
      multipleOf: 10
    - name: range
      title: Range with default
      default: 28
      type: integer
    - name: rangeConstrained
      title: Range with constraints
      type: integer
      minimum: -50
      maximum: 50
      multipleOf: 25
