action:
  title: Setup platform domains
  description: Enter a name to personalize your platform interface.
  image: alpine:latest
  command: ["sh", "-c", "for i in $(seq 10); do echo -e \"\\033[32m$$i\\033[0m\"; sleep 1; done"]
  options:
    - name: proddomain
      title: Prod Domain Name
      type: string
    - name: prodext
      title: Prod Domain Extension
      type: string
    - name: devdomain
      title: Dev Domain Name
      type: string
    - name: devext
      title: Dev Domain Extension
      type: string
    - name: sandboxdomain
      title: Sandbox Domain Name
      type: string
    - name: sandboxext
      title: Sandbox Domain Extension
      type: string
