export const initialNodes = [
  {
    id: 'start',
    position: { x: 0, y: 0 },
    data: { label: 'Platform name' },
    type: 'node-start',
  },
  {
    id: 'foundation',
    position: { x: 200, y: 0 },
    data: { label: 'Foundation' },
    type: 'node-wrapper',
    style: { width: 300, height: 250 },
  },
  {
    id: 'foundation.software',
    position: { x: 25, y: 25 },
    data: { label: 'Software' },
    type: 'node-wrapper',
    parentId: 'foundation',
    extent: 'parent',
    style: { width: 250, height: 200 },
  },
  {
    id: 'foundation.software.flatcar',
    position: { x: 25, y: 25 },
    data: { label: 'Flatcar' },
    type: 'node-wrapper',
    parentId: 'foundation.software',
    extent: 'parent',
    style: { width: 200, height: 150 },
  },
  {
    id: 'foundation.software.flatcar:bump',
    position: { x: 25, y: 25 },
    data: { label: 'Bump' },
    type: 'node-action',
    parentId: 'foundation.software.flatcar',
    extent: 'parent',
  },
  {
    id: 'foundation.software.flatcar:deploy',
    position: { x: 25, y: 75 },
    data: { label: 'Deploy' },
    type: 'node-action',
    parentId: 'foundation.software.flatcar',
    extent: 'parent',
  },
  {
    id: 'interaction',
    position: { x: 200, y: 300 },
    data: { label: 'Interaction' },
    type: 'node-wrapper',
    style: { width: 600, height: 430 },
  },
  {
    id: 'interaction.application',
    position: { x: 25, y: 25 },
    data: { label: 'Application' },
    type: 'node-wrapper',
    parentId: 'interaction',
    extent: 'parent',
    style: { width: 550, height: 380 },
  },
  {
    id: 'interaction.application.roles',
    position: { x: 25, y: 25 },
    data: { label: 'Roles' },
    type: 'node-wrapper',
    parentId: 'interaction.application',
    extent: 'parent',
    style: { width: 500, height: 330 },
  },
  {
    id: 'interaction.application.roles.erp',
    position: { x: 25, y: 25 },
    data: { label: 'Erp' },
    type: 'node-wrapper',
    parentId: 'interaction.application.roles',
    extent: 'parent',
    style: { width: 450, height: 80 },
  },
  {
    id: 'interaction.application.roles.erp:collect_data',
    position: { x: 25, y: 25 },
    data: { label: 'Collect Data' },
    type: 'node-action',
    parentId: 'interaction.application.roles.erp',
    extent: 'parent',
  },
  {
    id: 'interaction.application.roles.erp:generate_report',
    position: { x: 225, y: 25 },
    data: { label: 'Generate Report' },
    type: 'node-action',
    parentId: 'interaction.application.roles.erp',
    extent: 'parent',
  },
  {
    id: 'interaction.application.roles.mail',
    position: { x: 25, y: 125 },
    data: { label: 'Mail' },
    type: 'node-wrapper',
    parentId: 'interaction.application.roles',
    extent: 'parent',
    style: { width: 450, height: 80 },
  },
  {
    id: 'interaction.application.roles.mail:create_account',
    position: { x: 25, y: 25 },
    data: { label: 'Create Account' },
    type: 'node-action',
    parentId: 'interaction.application.roles.mail',
    extent: 'parent',
  },
  {
    id: 'interaction.application.roles.mail:send_mail_to_group',
    position: { x: 225, y: 25 },
    data: { label: 'Send mail to Group' },
    type: 'node-action',
    parentId: 'interaction.application.roles.mail',
    extent: 'parent',
  },
  {
    id: 'interaction.application.roles.messenger',
    position: { x: 25, y: 225 },
    data: { label: 'Messenger' },
    type: 'node-wrapper',
    parentId: 'interaction.application.roles',
    extent: 'parent',
    style: { width: 450, height: 80 },
  },
  {
    id: 'interaction.application.roles.messenger:create_account',
    position: { x: 25, y: 25 },
    data: { label: 'Create Account' },
    type: 'node-action',
    parentId: 'interaction.application.roles.messenger',
    extent: 'parent',
  },
  {
    id: 'interaction.application.roles.messenger:create_channel',
    position: { x: 225, y: 25 },
    data: { label: 'Create Channel' },
    type: 'node-action',
    parentId: 'interaction.application.roles.messenger',
    extent: 'parent',
  },
  {
    id: 'integration',
    position: { x: 1000, y: 200 },
    data: { label: 'Integration' },
    type: 'node-wrapper',
  },
  {
    id: 'platform',
    position: { x: 1000, y: 0 },
    data: { label: 'Platform' },
    type: 'node-wrapper',
  },
]

export const initialEdges = [
  {
    id: 'start-foundation',
    source: 'start',
    target: 'foundation',
    type: 'smoothstep',
  },
  {
    id: 'start-interaction',
    source: 'start',
    target: 'interaction',
    type: 'smoothstep',
  },
  {
    id: 'start-integration',
    source: 'start',
    target: 'integration',
    type: 'smoothstep',
  },
  {
    id: 'start-platform',
    source: 'start',
    target: 'platform',
    type: 'smoothstep',
  },
]
